version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    reviewers:
      - "eigerco/beerus"
