---
blank_issues_enabled: false
contact_links:
  - name: Beerus Community Support
    url: https://github.com/keep-starknet-strange/beerus/discussions
    about: Please ask and answer questions here.
