[package]
description = "JSON-RPC server for the Beerus Light Client"
edition = "2021"
name = "beerus-rpc"
version = "0.3.0"

[dependencies]
beerus-core = { path = "../core" }
eyre.workspace = true
jsonrpsee = { version = "0.20.3", features = [
  "macros",
  "server",
  "server-core",
] }
starknet.workspace = true
thiserror = "1.0.50"

[dev-dependencies]
wiremock = "0.5.19"
rstest = "0.18.2"
