[package]
description = "JSON-RPC server for the Beerus Light Client"
edition = "2021"
name = "beerus-rpc"
version = "0.4.0"

[features]
integration-tests = ["pretty_assertions", "cached"]

[dependencies]
beerus-core = { path = "../core" }
cached = { version = "0.49.3", optional = true }
starknet.workspace = true
eyre.workspace = true
jsonrpsee = { version = "0.20.3", features = ["macros", "server", "server-core"] }
pretty_assertions = { version = "1.4.0", optional = true }
serde = { workspace = true, features = ["derive"] }
serde_with.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
lazy_static = "1.4.0"
serde_json = "1.0"
reqwest = "0.11.13"
tokio.workspace = true
