[package]
description = "JSON-RPC server for the Beerus Light Client"
edition = "2021"
name = "beerus-rpc"
version = "0.2.0"

[dependencies]
beerus-core = { path = "../core" }
jsonrpsee = { version = "0.20.3", features = [
  "macros",
  "server",
  "server-core",
] }
starknet.workspace = true
thiserror = "1.0.50"
