[package]
description = "Examples for the Beerus Light Client"
edition = "2021"
name = "example"
version = "0.3.0"

[dependencies]
beerus-core = { path = "../../crates/core"}
tracing-subscriber.workspace = true
tracing.workspace = true
starknet.workspace = true
eyre.workspace = true
async-std = { workspace = true, features = ["attributes", "tokio1"] }


[[example]]
name = "basic"
path = "basic.rs"

[[example]]
name = "call"
path = "call.rs"
