network = "MAINNET"
eth_execution_rpc = "https://eth-mainnet.g.alchemy.com/v2/<YOUR API KEY>"
starknet_rpc = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0.6/<YOUR API KEY>"
data_dir = "tmp"
poll_secs = 5
rpc_addr = "127.0.0.1:3030"
