network = "MAINNET"
eth_execution_rpc = "https://eth-mainnet.g.alchemy.com/v2/Lv20XXhxC-kQRAWSuq2x86tkgkc1dJ0o"
starknet_rpc = "https://starknet-mainnet.g.alchemy.com/v2/F7nykNu-TMfyUpg8Snk8Shjn_icNjzfu"
data_dir = "tmp"
poll_secs = 5
rpc_addr = "127.0.0.1:8080"
