[book]
authors = ["Beerus Team"]
language = "en"
multilingual = false
src = "src"
title = "Beerus Documentation"

[build]
extra-watch-dirs = ["po", "third_party"]

[preprocessor.gettext]
after = ["links"]

[output.html]
curly-quotes = true
additional-css = ["css/language-picker.css"]
git-repository-url = "https://github.com/keep-starknet-strange/beerus"
no-section-label = true 

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true