name: mdbook
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - book/**

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install mdbook
        run: cargo install mdbook --locked --version 0.4.28
        shell: bash
  
      - name: Install mdbook-i18n-helpers
        run: cargo install mdbook-i18n-helpers --locked --version 0.1.0
        shell: bash
  

      - name: Build in English
        run: |
          cd book
          mdbook build -d book

      - name: Build all translations
        run: |
          cd book
          for po_lang in $(cat ./LANGUAGES); do
              echo "::group::Building $po_lang translation"
              MDBOOK_BOOK__LANGUAGE=$po_lang \
              mdbook build -d book/$po_lang
              ls book/$po_lang
              echo "::endgroup::"
          done

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./book/book

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
