name: rust-integration-tests-alchemy
on:
  schedule:
    - cron: "0 8,20 * * *"
  push:
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: build beerus
        run: cargo build -p beerus-cli --release

      - name: start beerus RPC on MAINNET
        env:
          ETH_EXECUTION_RPC: ${{ secrets.ETH_EXECUTION_RPC_MAINNET }}
          STARKNET_RPC: ${{ secrets.STARKNET_RPC_0_6_0_MAINNET_ALCHEMY }}
        # Start Beerus, then try to reach the port every second for 60 seconds.
        run: ./target/release/beerus & for i in {1..60}; do timeout 1 bash -c "echo > /dev/tcp/localhost/3030" 2> /dev/null && break || sleep 1; done

      - name: run integration test on MAINNET
        run: cargo test --package beerus-rpc --features integration-tests

      - name: stop RPC
        run: kill $(lsof -t -i:3030)
 